### PR TITLE
Added session creation to jboss-node-name

### PR DESCRIPTION
**Pull request by honza-kasik**
just to create a session and get JSESSIONID cookie.

cc @tommaso-borgato

### CODE REVIEW

**Comment by rhusar** [comment]
@honza-kasik I think this is probably fine, but can you describe the motivation for the change? This servlet is supposed to just expose the the node name. If a test is using this servlet without preserving state, this can create unnecessary and unexpected sessions.

**Comment by rhusar** [comment]
Also, if you are creating a session, they you don't even need this servlet, because you would typically know the node name from the routing information added to the session ID...

**Comment by honza-kasik** [comment]
Sorry, I forgot to mention. This is associated with mod_cluster testing and adapting for Jakarta EE 10. This is the only clusterbench fork in existence which was adapted that way. Old fork which was in use before uses `jvm-route` servlet which contains apparently creates session (`JSESSIONID` is being obtained from there). I'm in process of updating tests and this is the solution.

**Comment by rhusar** [comment]
Regarding the forks, this project meant to end all of that, why forks were created and never pushed here I don't know. There is a https://github.com/clusterbench/clusterbench/issues/51 for which an attempt was made but got out of date and never rebased.

**Comment by rhusar** [comment]
> I'm in process of updating tests and this is the solution.

I see it's becoming clear that it's the test that needs to be fixed, rather than the servlet since this has consequences.

**Comment by honza-kasik** [comment]
> I see it's becoming clear that it's the test that needs to be fixed, rather than the servlet since this has consequences.

That's one of the options. Currently tests depend on a servlet which provides both - a node name in response and an active session. This means that client will receive `JSESSIONID` cookie.

This PR is rather restoring compatibility which would be otherwise resolved in #51 .

**Comment by rhusar** [comment]
@honza-kasik So the other option is to add a servlet that does both...

**Comment by honza-kasik** [comment]
@rhusar Yes, if that's a preferred solution, I have no issues with that. Perhaps naming its route "jboss-node-name-session"?

**Comment by rhusar** [comment]
@honza-kasik replaced by https://github.com/clusterbench/clusterbench/pull/260 including a test.

**Pull request closed without merging**
