### PR TITLE
added 2clusters profile for 2clusters tests

### PR DESCRIPTION
**Pull request by tommaso-borgato**
needed and EAR with a different implementation of some EJB that do the call forwarding

### CODE REVIEW

**Comment by rhusar** [comment]
@tommaso-borgato The commit metadata seems still incorrect -- its not linking to your github account.

**Comment by tommaso-borgato** [comment]
> @tommaso-borgato The commit metadata seems still incorrect -- its not linking to your github account.

@rhusar I don't understand what's wrong

**Comment by rhusar** [comment]
@tommaso-borgato This is wrong, not a valid email address

```
Refs: {tborgato/2clusters}, 3.0.0.Final-15-g112a6c8
Author:     tborgato <tborgato@tborgato.redhat.com>
AuthorDate: Fri Jun 21 19:10:28 2019 +0200
Commit:     tborgato <tborgato@tborgato.redhat.com>
CommitDate: Fri Jun 21 19:10:28 2019 +0200
```

**Comment by tommaso-borgato** [comment]
@rhusar is it ok now?

**Pull request merged**
