### PR TITLE
Added request parameters and URI to debug servlet

### PR DESCRIPTION
**Pull request by honza-kasik**
Added information about request parameters and request URI into the `/debug` servlet. Request parameters in response are parsed by a few tests.

### CODE REVIEW

**Comment by honza-kasik** [comment]
Hello @rhusar ! Will you please have some time in the near future to look at this PR?

**Comment by rhusar** [comment]
Hey @honza-kasik  I ll do this today.

**Review by rhusar — APPROVED** [review]
LGTM

There's a trailing extraneous new line (both println and \n) but I ll fix it up.

**Comment by rhusar** [comment]
Fixup PR: https://github.com/clusterbench/clusterbench/pull/280

**Comment by rhusar** [comment]
Done now. Thanks @honza-kasik !

**Comment by rhusar** [comment]
@honza-kasik Just to note here, this is missing an associated test case / expanding existing test case - opened https://github.com/clusterbench/clusterbench/issues/304

**Pull request merged**
