### PR TITLE
Added memory usage servlet, closes #282

### LINKED ISSUE #282: Missing servlet for stressing memory
Same as https://github.com/Karm/clusterbench/blob/simplified-and-pure/clusterbench-ee7-web/src/main/java/org/jboss/test/clusterbench/web/load/MemoryUsageServlet.java

This is used in mod_cluster tests

I suggest adding this as a new servlet to `load` package.

### PR DESCRIPTION
**Pull request by honza-kasik**
Straight copied from Same as https://github.com/Karm/clusterbench/blob/simplified-and-pure/clusterbench-ee7-web/src/main/java/org/jboss/test/clusterbench/web/load/MemoryUsageServlet.java + migrated to Jakarta EE

### CODE REVIEW

**Comment by rhusar** [comment]
@tommaso-borgato Do you also want to add your review?

**Comment by tommaso-borgato** [comment]
@rhusar that's fine for me: it doesn't modify any existing behavior

**Review by rhusar — APPROVED** [review]
I am going to approve this although, this is missing tests and documentation. I will create post-merge issue to track this.

**Comment by rhusar** [comment]
Thanks @honza-kasik @tommaso-borgato ! Merging to 5.x.

**Comment by rhusar** [comment]
@honza-kasik Opened https://github.com/clusterbench/clusterbench/issues/302 to track this.

**Pull request merged**
