### PR TITLE
Jakarta

### PR DESCRIPTION
**Pull request by tommaso-borgato**
In this pull request:

- Jakarta EE 10 variant 
- core profile for lightwight clusterbench

### CODE REVIEW

**Comment by tommaso-borgato** [comment]
@rhusar can you have a look?

**Comment by rhusar** [comment]
@tommaso-borgato As I mentioned I also have a branch for this, with more changes shuffling around (e.g. into respective directories so that we can enable dependabot for each), but I ll just review and merge this one :-)

**Comment by rhusar** [comment]
Also, not quite sure why the tests didn't run..?

**Comment by rhusar** [comment]
@tommaso-borgato The tests are failing when running locally...

> Caused by: java.lang.ClassNotFoundException: jakarta.faces.webapp.FacesServlet from [Module "deployment.clusterbench-jakarta10.ear.clusterbench-jakarta10-web-passivating.war" from Service Module Loader]

**Comment by rhusar** [comment]
I will merge this as is and apply fixes afterwards.

**Pull request merged**
