### PR TITLE
Added servlet to stop the server, closes #283

### LINKED ISSUE #283: Failover servlet missing
Add  a servlet which would allow to destroy the server without triggering shutdown hooks.

### PR DESCRIPTION
**Pull request by honza-kasik**

### CODE REVIEW

**Comment by rhusar** [comment]
@tommaso-borgato Do you also want to add your review? I am a little bit worried if this can cause issues ie. by being accidentally called, but as long as we don't link to this it's a nifty simple way to test a failure.

**Comment by tommaso-borgato** [comment]
@rhusar it's fine for me... if you don't call it there no issue

**Review by rhusar — CHANGES_REQUESTED** [review]
@honza-kasik So how about we consult a property that allows server restart? 

    ./standalone.sh ... -Dorg.jboss.test.cluster.allow-exit-servlet

Would that be a problem? i.e. that way it would need to be explicitly allowed.

**Comment by honza-kasik** [comment]
> @honza-kasik So how about we consult a property that allows server exit?
> 
> ```
> ./standalone.sh ... -Dorg.jboss.test.clusterbench.allow-exit-servlet=true
> ```
> 
> Would that be a problem? i.e. that way it would need to be explicitly allowed and only used in tests that are actually using it.

What about using parameter in the query instead? Something like: `.../exit?confirm=true`. We could start the server as usual and also prevent accidental trigger.

**Review by rhusar — APPROVED** [review]

**Comment by rhusar** [comment]
Thanks @honza-kasik @tommaso-borgato !

**Pull request merged**
